# Legacy parameters for deprecated polis pipeline
# polis_id: r2xcn2cdbmrzjmmuuytdk # American Assembly Bowling Green 2018
# polis_id: r7cwmiaxczyj8te9rzdmx # DemDis EU isolation

# PCA Subpipeline Parameters
pca:
  n_components: 2
  flip_x: true
  flip_y: false

# Geographic projection parameters
geographic:
  geojson_path: "data/r7bhuide6netnbr8fxbyh/01_raw/san-juan-islands.minimal.geojson"
  output_path: "data/08_reporting/participants_points.geojson"
